spring:
  profiles:
    active: dev



#java -jar target/demo-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod

mybatis:
  mapperLocations: mapper/*/*.xml
  config-location: classpath:config/mybatis-config.xml

