spring:
  profiles:
    active: dev

  redis:
    host: localhost
    port: 16379
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
      max-wait: 1000
    database: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true
    virtual-host: /




#java -jar target/demo-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod

mybatis:
  mapperLocations: mapper/*/*.xml
  config-location: classpath:config/mybatis-config.xml

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# 配置logback
logging:
  config: classpath:logback.xml
